### ISSUE TITLE
Imatex, MET, Garin and VAM do not have permanent URI for their images 

### ISSUE THREAD

**Issue by tschleider** [silknow/converter#13] opened 2019-05-23 14:36 UTC
- In case of Imatex the conversion has to be changed and then applied
- Solution for VAM is on its way (converter updated, conversion ongoing)
- In case of Garin all images have been already uploaded, conversion needs to add reference to their location
- In case of MET the main error is connected to #12

**Comment by rtroncy** [comment] 2019-05-23 14:42
/ cc @javier-sevilla to let us know about the status of the local copy of all images on the SILKNOW server

**Comment by javier-sevilla** [comment] 2019-05-24 08:30
The base link is: http://silknow.org/silknow/media/ 
followed by the name of the data provider (garin, imatex, etc.), and optionally some sub-folders (e.g. for garin, tejidos, puestas_en_carta, etc), and the name of the file. For instance: http://silknow.org/silknow/media/garin/tejidos/T001139_ANV.jpg

The folders and the name of the data provider follow the same format than on owncloud (with "_" replacing white space)

- http://silknow.org/silknow/media/garin/tejidos/
- http://silknow.org/silknow/media/garin/puestas_en_carta/
- http://silknow.org/silknow/media/garin/dibujos
- http://silknow.org/silknow/media/ceres-mcu/
- http://silknow.org/silknow/media/imatex/
- http://silknow.org/silknow/media/joconde/
- http://silknow.org/silknow/media/les-arts-decoratifs/
- http://silknow.org/silknow/media/met-museum/
- http://silknow.org/silknow/media/mfa-boston/
- http://silknow.org/silknow/media/mtmad/
- http://silknow.org/silknow/media/vam/
- http://silknow.org/silknow/media/risd-museum/

Listing all files in a specific folder is prevented using .htaccess for security reasons. It is necessary to access directly to the files, for instance:
- http://silknow.org/silknow/media/garin/tejidos/T001139_ANV.jpg
- http://silknow.org/silknow/media/imatex/0000014514.jpg
- http://silknow.org/silknow/media/ceres-mcu/CE23971_MNAD_2.jpg

**Comment by rtroncy** [comment] 2019-05-24 08:47
Thanks @javier-sevilla . I have updated your comment for better readability.

**Comment by tschleider** [comment] 2019-05-28 13:24
Status update: 
- Fixed the converter for VAM, MET and IMATEX accordingly
- Re-uploaded VAM, MET and the English version of IMATEX so far

**Comment by tschleider** [comment] 2019-06-06 11:20
Status update:
- Re-upload of IMATEX completed
- Only GARIN left with no working URIs
- Next step is to add links to our local copies for all datasets 

@javier-sevilla : Is it actually possible to change the folder structure for GARIN? Could you just copy all images of Garin to http://silknow.org/silknow/media/garin/ instead of the three subfolders?

**Comment by rtroncy** [comment] 2019-06-06 12:25
There was an added-value in keeping this sub-folder structure for the GARIN dataset images. Why would you need to put all images in the root folder? Given a metadata file, you know how to re-create this path, right?

**Comment by javier-sevilla** [comment] 2019-06-06 12:36
Yes sure, is possible, only some cp commands. 
I'll do at 15.30.

**Comment by tschleider** [comment] 2019-06-06 12:36
@rtroncy : Right now this information is not kept in the conversion, the images are connected to the record by their filename, not their full path. Is this added-value worth it to rewrite the converter?

**Comment by rtroncy** [comment] 2019-06-06 12:57
@javier-sevilla Please, wait for the discussion to be finished on github
@tschleider We will loose the knowledge that some images are "dibujos" or "tejidos" or "puesta en carta", or can you found this information in the metadata? I think it is worth to keep it. How hard is it to adapt the converter to maintain this folder structure?

**Comment by tschleider** [comment] 2019-06-06 13:29
Actually there is one field ("Objecto") that roughly corresponds to these three categories, but not always. To give you an example, most records in the tejido folders have the "Objecto" set as "Tejido", but once in a while i see a record like G.P.00482 which is in the "Puesta en carta" folder and has this field set to "Patrón", which sounds to me like it is either more fine-grained than these 3 folders or the whole classification is not exact. Either way I could check how much variation we have there and re-integrate these sub-folder paths into the converter, but we probably do not lose information by just dropping them for the image paths and it would make things a bit easier.

**Comment by javier-sevilla** [comment] 2019-06-06 14:01
oK , sure, don't worry. I expect to the final decision.

**Comment by rtroncy** [comment] 2019-06-06 15:58
Let's ask Garin for their opinion. I'm making an email.

**Comment by rtroncy** [comment] 2019-06-07 13:26
Following the discussion we had by emails, all GARIN images are now in a single /garin folder. @tschleider you can therefore close this issue when the converter rightly implements this behavior

**Comment by tschleider** [comment] 2019-07-11 15:09
@javier-sevilla I now finally implemented the changes to make the garin converter use the local copy with the updated folder structure, but the URI still does not work, e.g.: "http://silknow.org/silknow/media/garin/GP007841.jpg" Is something wrong with the URI or the image, Javier?

**Comment by tschleider** [comment] 2019-08-22 15:33
@javier-sevilla We implemented some mechanism to add the URL for our local copies of the images for almost all converters (except CER, UNIPA and MTMAD), but I still do not know what is wrong with the URLs for Garin ( see above, http://silknow.org/silknow/media/garin/GP007841.jpg ), VAM and MAD. 

Here examples for the latter ones, what is wrong the the URLs?

VAM: http://silknow.org/silknow/media/vam/2011ER1133.jpg
MAD: http://silknow.org/silknow/media/les-arts-decoratifs/41dbf0d0-e5bf-41ac-a95b-da9ee7dfc775.jpg

**Comment by javier-sevilla** [comment] 2019-10-04 15:09
Hello @tschleider 

I have checked the wrong link with a GARIN image:
http://silknow.org/silknow/media/garin/GP007841.jpg

In the computer there are two files

GP00784_REV.jpg, GP00784_ANV.jpg  but there isn't the GP007841.jpg file.

I'll check the VAM and MAD missing giles

Sorry for the delay I was off during two months.

**Comment by rtroncy** [comment] 2019-10-04 20:11
Indeed, I just did a search in owncloud with the string `GP00784` and I get only 3 files: GP00784.xls, GP00784_ANV.jpg and GP00784_REV.jpg. There are duplicates, stored both in `/data/garin/Puesta en carta/Palacio Alemán/Fotografías Patrones Palacio Alemán/` and in `/GARIN/Puesta en carta/Palacio Alemán/Fotografías Patrones Palacio Alemán/`

However, the pattern for GARIN is that the excel filename leads to the jpg image filenames right?

**Comment by javier-sevilla** [comment] 2019-10-07 12:35
There are not duplicates, the three files are all related with the same textile.

The excel file is a file with text data and also the images embbeded into the excel file.
The jpg files are the images contained inside the excel (ANV is the front of the textile, REV is the back of the textile)

This fact is the same with many GARIN files.

**Comment by rtroncy** [comment] 2019-10-07 14:11
@javier-sevilla I''m not saying that GP00784_REV.jpg and GP00784_ANV.jpg are duplicates, there are not! What I'm saying is that the files GP00784_REV.jpg, GP00784_ANV.jpg and GP00784.xls are present twice on owncloud, in the path folder `/data/garin/Puesta en carta/Palacio Alemán/Fotografías Patrones Palacio Alemán/` AND in the path folder `/GARIN/Puesta en carta/Palacio Alemán/Fotografías Patrones Palacio Alemán/` This is the case for numerous files since you have copied all museums data in /data without deleting the per institution folders.

Now, the issue is: how do we go guess the image names GP00784_REV.jpg and GP00784_ANV.jpg from the excel filename GP00784.xls? Is there a recipe?

**Comment by javier-sevilla** [comment] 2019-10-07 15:49
Oh, yes, don't worry about that. This is a question of owncloud folders. In the beggining each partner put the data in its own folder, but in its folder there are textile data and also other project files. In order to avoid misunderstandings we create the folder "data" with only museum data inside. You only need to check textile data from the "data" folder. We decided that many months ago I should delete the original files in order to avoid this problems, with all the partners agreement, I'll do it asap. Sorry for the inconveniences.

**Comment by tschleider** [comment] 2019-10-07 16:00
I just realised that @pasqLisena  coded a mechanism to give the TTL files a note if they have an "anverso" or "reverso" image, but the mechanism is not applied to the relevant part for images. I am sure we can use it for the URL "construction".

@pasqLisena : Do you have any input on this, I see that right now it creates these URIs, and I do not fully understand it (taken from GP00784.ttl) :

```ttl
<http://data.silknow.org/object/269122e8-44b2-3010-8fea-7aa0be9a5d92/section/Anverso>
        a                          ecrm:E53_Place ;
        rdfs:label                 "Anverso" ;
        ecrm:P87_is_identified_by  "Anverso" .
```

**Comment by pasqLisena** [comment] 2019-10-08 08:37
Hi,
that part is coded in the [garin converter](https://github.com/silknow/converter/blob/master/src/main/java/org/silknow/converter/converters/GarinConverter.java#L117), on the base of rules coming from [the mapping table](https://docs.google.com/document/d/1_DMd0aF4aweBmBKBMV11aUYzttqGT2ecTFAAJ0vNT6E/edit).

In particular:


Field | Example | Main Class | Path 
-- | -- | -- | -- 
Anverso | No | S4_Observation | E22_ Man-Made Object P59 has section E53_Place P87 is identified by E46_Section Definition S4_Observation 08 observed E53_PlaceS4_Observation P3 has note E62_StringS4_Observation P2 has type E55_Type (Anverso)
Reverso | Etiqueta adhesiva “MG Valencia 11” | S4_Observation | E22_ Man-Made Object P59 has section E53_Place P87 is identified by E46_Section Definition  S4_Observation 08 observed E53_PlaceS4_Observation P3 has note E62_StringS4_Observation P2 has type E55_Type (Reverso)

**Comment by javier-sevilla** [comment] 2019-11-14 08:39
Hi Raphael,

I think that duplicated file names are due to the duplicity of folders.

The valid files will be saved in:

/data/garin/Puesta en carta/Palacio Alemán/Fotografías Patrones Palacio Alemán/

The other files will be removed next monday.

**Comment by rtroncy** [comment] 2019-11-14 08:51
@javier-sevilla 
We have to distinguish how things are stored on the owncloud server from what is served from http://silknow.org/silknow/media/ !

For GARIN, please no! We agreed to flatten the hierarchy. So ALL images need to be served from http://silknow.org/silknow/media/garin and no sub-folders!

Note: I edit your previous reply. If you reply to email, please, strip out past messages or go edit the comment directly on github, otherwise, it becomes unreadable on github.

**Comment by javier-sevilla** [comment] 2019-11-14 11:57
OK, I'll write a text file in owncloud describing how the files a saved into silknow/media if the structure is different. Something like in every folder "CHANGES_STRUCTURES.txt". 

It is difficult and slow to copy hundred of files with owncloud. And at the end, owncloud is just for human consulting .

**Comment by tschleider** [comment] 2019-11-19 15:56
I checked my Garin example again and realised the file GP007841.jpg does not exist in the original Garin dataset, but  GP00784_REV.jpg, GP00784_ANV.jpg get changed into GP007841.jpg and GP007842.jpg after conversion. Can you confirm that @pasqLisena ? I guess we can change that back and then we're good with Garin!

http://silknow.org/silknow/media/garin/GP00784_ANV.jpg

For the other examples, 

VAM: http://silknow.org/silknow/media/vam/2011ER1133.jpg

is working now, but 

MAD: http://silknow.org/silknow/media/les-arts-decoratifs/41dbf0d0-e5bf-41ac-a95b-da9ee7dfc775.jpg

still isn't. Any idea about that?

**Comment by javier-sevilla** [comment] 2019-11-20 09:50
Hi Thomas,

Where did you get the file name of les arts decoratifs? Maybe from a JSON file? I don't find that name in owncloud.

**Comment by tschleider** [comment] 2019-11-20 15:44
https://silknow.uv.es/owncloud/index.php/apps/files/?dir=/SILKNOW/TEMPORAL_DATA%20(removed%20soon)&fileid=144701

It's in the "files" archives. As I said, right now only this folder contains the most up-to-date crawling results (and should not be removed, rather moved).

**Comment by rtroncy** [comment] 2019-11-20 22:28
@javier-sevilla You need to make sure that what you served from http://silknow.org/silknow/media/{museum} is the latest version of what we crawled. See the previous messages on the list

**Comment by rtroncy** [comment] 2019-12-03 17:55
@javier-sevilla Can you please update us on this issue? We can still find some UNIPA links that do not work, e.g. http://silknow.org/silknow/media/unipa/mudipa1.4.jpg. Are you still working on it?

**Comment by javier-sevilla** [comment] 2019-12-04 09:50
I check now and I'll tell you something asap.

Javier.

**Comment by javier-sevilla** [comment] 2019-12-04 10:04
Hola

I don't know what happened, we execute the script again and the files are right copied.

Regards,
Javier.

**Comment by tschleider** [comment] 2019-12-08 23:44
Thanks again @javier-sevilla . After some updates on the MET crawler (and their website), we needed to recrawl the dataset again. Could you (hopefully the last time before Hannover) please replace the old MET images with the one from 

https://silknow.uv.es/owncloud/index.php/apps/files/?dir=/SILKNOW/TEMPORAL_DATA%20(removed%20soon)&fileid=144701

? Thank you!

**Comment by tschleider** [comment] 2019-12-09 14:28
This becomes more and more of a non-stop problem, but right now everything should work, but images from our latest MFA crawl are not on the media-server, could you have a look at them, too, @javier-sevilla ? Thank you!

**Comment by tschleider** [comment] 2019-12-09 14:45
@rtroncy : Everything is implemented on the crawler and converter side and working. Shall we already close it? I can also email about dead links in the future / ask for uploads.

**Comment by rtroncy** [comment] 2019-12-09 14:49
Let's close the issue once @javier-sevilla has copied all the necessary images on the media server

**Comment by javier-sevilla** [comment] 2019-12-09 16:48
Done!!

Sorry for the delay.

Javier.

**Comment by tschleider** [comment] 2019-12-09 17:07
@javier-sevilla thanks but, see example links (belonging to my last comments above):
MET:  http://silknow.org/silknow/media/met-museum/DP820005.jpg
MFA: http://silknow.org/silknow/media/mfa-boston/SC14033.jpg

**Comment by tschleider** [comment] 2019-12-11 00:20
The links are working, shall I dare to close it or does somebody want to do another check? 

[Very large query that returns the illustrating image of each man made object across all museums](http://data.silknow.org/sparql?default-graph-uri=&query=prefix+crmdig%3A+%3Chttp%3A%2F%2Fwww.ics.forth.gr%2Fisl%2FCRMext%2FCRMdig.rdfs%2F%3E++%0D%0Aprefix+crmsci%3A+%3Chttp%3A%2F%2Fwww.ics.forth.gr%2Fisl%2FCRMsci%2F%3E%0D%0ASELECT+DISTINCT+%3Fg+%3Fid+%3Fobj+%3Furl+%0D%0AWHERE+%7B%0D%0A++GRAPH+%3Fg+%7B%0D%0A+++++%3Fdig+a+crmdig%3AD1_Digital_Object+.+%7D%0D%0A++%0D%0A++++++%3Fdig+ecrm%3AP129_is_about+%3Fobj+.%0D%0A++++++%3Fobj+a+ecrm%3AE22_Man-Made_Object+.%0D%0A++++++%3Fobj++dc%3Aidentifier+%3Fid+.%0D%0A++++++%3Fobj+ecrm%3AP138i_has_representation+%3Furl1+.%0D%0A++++++%3Furl1+schema%3AcontentUrl+%3Furl.%0D%0A%0D%0AFilter+contains%28str%28%3Furl%29%2C%22silknow%22%29%0D%0A%7D&format=text%2Fhtml&timeout=0&debug=on)

**Comment by pasqLisena** [comment] 2019-12-18 15:13
For completeness, since 0d3e897 the Images in Garin may have a `P2 has type` with `anverso`, `reverso` or `detail` as value. You may probably want to change the first 2 in `recto` / `verso` in the future

**Comment by rtroncy** [comment] 2019-12-18 21:05
I agree and I'm therefore re-opening this issue that should be closed only when the value of the `P2_has_type` property will be converted into English (or a controlled vocabulary).

**Comment by pasqLisena** [comment] 2019-12-19 14:07
We go for recto/verso or we need an agreement between SILKNOW project members?

**Comment by rtroncy** [comment] 2019-12-19 16:01
We go for recto/verso.

**Closed as completed** 2019-12-19 17:42 UTC
Labels: bug
